// get all tours
GET http://127.0.0.1:3000/api/v1/tours HTTP/1.1


###
// get tour by id
GET http://127.0.0.1:3000/api/v1/tours/5c88fa8cf4afda39709c2955/Point HTTP/1.1

###
// create a new tour
POST http://127.0.0.1:3000/api/v1/tours HTTP/1.1
content-type: application/json

{
    "name": "Test",
    "duration": 7,
    "maxGroupSize": 15,
    "difficulty": "medium"
}